### ISSUE TITLE
Missing Resources

### ISSUE THREAD

**Issue by blusechen** [XanTheDragon/Spiral-Knights-Animator-Tools#1]
public ImageIcon info = loadImage("info.png");
	public ImageIcon object = loadImage("object.png");
	public ImageIcon sky = loadImage("sky.png");
	public ImageIcon model = loadImage("model.png");
	public ImageIcon value = loadImage("value.png");
	public ImageIcon tag = loadImage("tag.png");
	public ImageIcon plug = loadImage("plug.png");
	public ImageIcon folder_gear = loadImage("folder_gear.png");
	public ImageIcon folder_wrench = loadImage("folder_wrench.png");
	public ImageIcon array = loadImage("array.png");
	public ImageIcon person = loadImage("person.png");
	public ImageIcon people = loadImage("people.png");
	public ImageIcon script = loadImage("script.png");
	public ImageIcon attachment = loadImage("hat.png");
	public ImageIcon derived = loadImage("derived.png");
	public ImageIcon script_part = loadImage("script_part.png");
	public ImageIcon part = loadImage("part.png");
	public ImageIcon partgroup = loadImage("partgroup.png");
	public ImageIcon animation = loadImage("animation.png");
	public ImageIcon unknown = loadImage("unknown.png");
	public ImageIcon none = loadImage("empty.png");

**Comment by XanTheDragon** [comment]
I'll investigate that. There should be a folder named "assets" inside of the JAR. Try extracting it out of the JAR so that it's in the same directory as the JAR file and tell me if that makes it work.

**Comment by XanTheDragon** [comment]
Sorry this is coming a bit later than expected. I'm investigating reports of other issues made externally that could be related to the reason you're having this issue.

**Comment by XanTheDragon** [comment]
Just released V1.0.0. This should fix this bug.
