### ISSUE TITLE
Any models that have children referencing other models overwrite the export data

### ISSUE THREAD

**Issue by XanTheDragon** [XanTheDragon/Spiral-Knights-Animator-Tools#3]
(This is being written for tracking on my own part.)

Any models that have nested attachments or model references will overwrite the export information, only leaving the lowest level model in the export.

**Comment by blusechen** [comment]
Hey, man, are you still doing this?

**Comment by XanTheDragon** [comment]
I've had some delays, unfortunately. Lots of schoolwork and things related. I forgot to remove the in-progress tag. I'll see if I can't try something today. Most of my work so far has been in rewriting the DAE exporting class to export bones.

**Comment by blusechen** [comment]
Thank you for your reply.  Is there any way to donate for the work?

**Comment by Airbee** [comment]
Hey, that thing is really cool helped me a lot! Thank you very much for that work!
Would really appreciate a .jar version where we also get the bones :)

**Comment by XanTheDragon** [comment]
Late update, I had a long delay during development again. It's pretty much done now, I just have to iron out the last few kinks.

**Comment by yihleego** [comment]
Is this project still updating?

**Comment by XanTheDragon** [comment]
Fixed with release 1.0.0.
